config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  get 'catalog/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  mount Ecomm::Engine => '/store'

  ActiveAdmin.routes(self)

  resources :books, only: :show do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :orders, only: [:index, :show]
  resource :settings, only: :show do
    resource :address, only: :update
    resource :email, only: :update
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  include Rectify::ControllerHelpers

  before_action(:authenticate_user!)

  def show
    present(SettingsPresenter.new, for: :main_app)
    present(Ecomm::CheckoutPresenter.new)
    address_service = Ecomm::Common::GetOrCreateAddress
    @billing = address_service.call(session, 'billing', current_user.id)
    @shipping = address_service.call(session, 'shipping', current_user.id)
  end
end

app/views/settings/_change_email.html.haml
%p.in-gold-500.font-18.mb-25= t('.caption')
= form_for(current_user, url: settings_email_path,
  class: 'general-form-md') do |f|
  .form-group.mb-35
    %label.control-label.font-weight-light{for: 'email'}= t('.enter_email')
    = f.email_field(:email, class: 'form-control',
      placeholder: t('.placeholder'))
  .general-text-align
    = f.submit(t('settings.show.save'), class: 'btn btn-default mb-35')

app/views/settings/_change_password.html.haml
%p.in-gold-500.font-18.mb-25= t('.caption')
= form_for(resource, as: resource_name, url: registration_path(resource_name),
  html: { method: :patch, class: 'general-form-md pb-25' }) do |f|
  = f.hidden_field(:reset_password_token)
  = f.hidden_field(:email, value: current_user.email)
  .form-group.mb-30
    %label.control-label.font-weight-light{for: 'currentPassword'}= |
      t('.old_password') |
    = f.password_field(:current_password, class: 'form-control',
      placeholder: t('.old_password'))
  .form-group.mb-30
    %label.control-label.font-weight-light{for: 'password'}= t('.new_password')
    = f.password_field(:password, class: 'form-control',
      placeholder: t('.new_password'))
  .form-group.mb-40
    %label.control-label.font-weight-light{for: 'confirmPassword'}= t('.confirm')
    = f.password_field(:password_confirmation, class: 'form-control',
      placeholder: t('.confirm'))
  .general-text-align
    = f.submit(t('.change'), class: 'btn btn-default mb-10')

app/views/settings/_remove_account.html.haml
%p.in-gold-500.font-18.mb-25.pt-20= t('.caption')
%form
  .general-settings-btn
    = link_to(t('.label'), registration_path(current_user),
      method: :delete, data: {confirm: t('.are_you_sure')},
      class: 'btn btn-default disabled mb-20', id: 'remove-account')
  .form-group.checkbox.general-settings-checkbox
    %label.font-weight-light.pl-0
      %input#remove-account-checkbox.checkbox-input{type: 'checkbox', |
        hidden: 'true'} |
      %span.checkbox-icon
        %i.fa.fa-check
      %span.checkbox-text= t('.understood')

app/views/settings/show.html.haml
%main.container
  %h1.general-title-margin= t('.caption')
  %ul.nav.nav-tabs.mb-20{role: 'tablist'}
    %li.mb-10{class: ('active' unless flash[:show_privacy]), role: 'presentation'}
      %a{href: '#address', 'aria-controls': 'address', role: 'tab', |
        'data-toggle': 'tab'}= t('.address') |
    %li.mb-10{class: ('active' if flash[:show_privacy]), role: 'presentation'}
      %a{href: '#privacy', 'aria-controls': 'privacy', role: 'tab', |
        'data-toggle': 'tab'}= t('.privacy') |
  .tab-content
    #address.tab-pane.general-main-wrap{class: ('active fade in' |
      unless flash[:show_privacy]), role: 'tabpanel'} |
      = form_for(@billing, url: settings_address_path, method: :put) do |f|
        .hidden-xs.hidden-sm
          .row
            .col-md-5
              %h3.general-subtitle.mt-0= presenter(:main_app).tr_billing
            .col-md-5.col-md-offset-1
              %h3.general-subtitle.mt-0= presenter(:main_app).tr_shipping
        .row
          .col-md-5.mb-40
            .visible-xs.visible-sm
              %h3.general-subtitle.mt-0= presenter(:main_app).tr_billing
            = render('ecomm/checkout/address_fields', f: f, address: @billing,
              type: 'billing', entity: 'address')
            .text-center.general-text-align
              = submit_tag(t('.save'), name: 'billing',
                class: 'btn btn-default')
          .col-md-5.col-md-offset-1.mb-25
            .visible-xs.visible-sm
              %h3.general-subtitle.mt-0= presenter(:main_app).tr_shipping
            = form_for(@shipping, url: settings_address_path,
              method: :put) do |f|
              = render('ecomm/checkout/address_fields', f: f, address: @shipping,
                type: 'shipping', entity: 'address')
            .text-center.general-text-align
              = submit_tag(t('.save'), name: 'shipping',
                class: 'btn btn-default')
    #privacy.tab-pane{class: ('active fade in' if flash[:show_privacy]), |
      role: 'tabpanel'} |
      .row.mb-60
        .col-sm-5
          = render('change_email')
        .col-sm-5.col-sm-offset-1
          = render('change_password')
        .col-sm-12
          = render('remove_account')