config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  get 'catalog/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  mount Ecomm::Engine => '/store'

  ActiveAdmin.routes(self)

  resources :books, only: :show do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :orders, only: [:index, :show]
  resource :settings, only: :show do
    resource :address, only: :update
    resource :email, only: :update
  end
end

app/models/ecomm/order.rb
require Ecomm::Engine.models_path(:order)

module Ecomm
  class Order
    include AASM

    aasm(column: 'state', whiny_transitions: false) do
      state(:in_progress, initial: true)
      state(:in_queue, :in_delivery, :delivered, :canceled)

      event(:queue) do
        transitions(from: :in_progress, to: :in_queue)
      end

      event(:deliver) do
        transitions(from: :in_queue, to: :in_delivery)
      end

      event(:complete) do
        transitions(from: :in_delivery, to: :delivered)
      end

      event(:cancel) do
        transitions(from: [:in_progress, :in_queue], to: :canceled)
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Rectify::ControllerHelpers

  before_action(:authenticate_user!)
  load_and_authorize_resource(class: Ecomm::Order, only: :index)

  def index
    present OrdersPresenter.new(params: order_params)
    return unless @orders
    filter = order_params[:filter]
    @orders = @orders.order('id desc')
    @orders = @orders.where(state: filter) if filter
    @orders = OrderDecorator.decorate_collection(@orders)
  end

  def show
    @order = Orders::GetOrderWithAssociated.call(order_params[:id])
    authorize!(:show, @order)
    present Ecomm::CheckoutPresenter.new
    @billing = @order.billing_address
    @shipping = @order.shipping_address || @billing
    @line_items = @order.line_items
  end

  private

  def order_params
    params.permit(:id, :filter)
  end
end

app/views/orders/_order.html.haml
%tr.order-row{'data-link': "#{order_path(order)}"}
  %td
    %span.general-order-number= order.number
  %td
    %span.in-grey-900.font-16.font-weight-light= order.created_at.strftime('%F')
  %td
    %span.font-16.in-grey-900
      .font-weight-light{class: ('text-success' |
        if order.state == 'delivered')}= order.state.humanize |
  %td
    %strong.font-16= number_to_currency(order.subtotal + order.shipment.price)

app/views/orders/_orders_filters.html.haml
%p.in-grey-600.small.mb-10.visible-xs= t('catalog.index.sort_by')
.dropdown.general-order-dropdown.mb-20
  %a.dropdown-toggle.dropdown-btn{href: '#', 'data-toggle': 'dropdown',
    role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'}
    = t(".#{presenter.current_orders_filter}")
    %i.fa.fa-angle-down.dropdown-icon
  %ul.dropdown-menu
    %li
      = link_to(t('.all'), presenter.params.to_h.except!(:filter))
    - presenter.filters.each do |filter|
      %li
        = link_to(t(".#{filter}"), presenter.params.merge(filter: filter))

app/views/orders/_xs_order.html.haml
.general-cart-item.divider-lg-bottom.pt-0.mb-20
  %table.table.order-row{'data-link': "#{order_path(order)}"}
    %tr
      %td.col-half
        %span.in-grey-600= t('orders.index.number')
      %td.col-half
        %span.general-order-number= order.number
    %tr
      %td
        %span.in-grey-600= t('orders.index.completed_at')
      %td
        %span.in-grey-900.font-16.font-weight-light= order.created_at.strftime('%F')
    %tr
      %td
        %span.in-grey-600= t('orders.index.status')
      %td
        %span.font-16.in-grey-900
          .font-weight-light{class: ('text-success' |
            if order.state == 'delivered')}= order.state.humanize |
    %tr
      %td
        %span.in-grey-600= t('orders.index.total')
      %td
        %strong.font-16= number_to_currency(order.subtotal + order.shipment.price)

app/views/orders/index.html.haml
%main.container.general-main-wrap
  %h1.mt-0.mb-25= t('.my_orders')
  = render('orders_filters')
  - if @orders.blank?
    .container.text-center.mt-100
      %h2= t('.no_orders')
  - else
    .visible-xs
      = render(partial: 'xs_order', collection: @orders, as: :order)
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th
              %span.in-grey-600= t('.number')
            %th
              %span.in-grey-600= t('.completed_at')
            %th
              %span.in-grey-600= t('.status')
            %th
              %span.in-grey-600= t('.total')
        %tbody
          = render(partial: 'order', collection: @orders)

app/views/orders/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= @order.number
  = render('ecomm/checkout/order_details', render_links: false)