config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  get 'catalog/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  mount Ecomm::Engine => '/store'

  ActiveAdmin.routes(self)

  resources :books, only: :show do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :orders, only: [:index, :show]
  resource :settings, only: :show do
    resource :address, only: :update
    resource :email, only: :update
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to(:category)
  has_and_belongs_to_many(:authors)
  has_and_belongs_to_many(:materials)
  has_many(:line_items, class_name: 'Ecomm::LineItem', foreign_key: :product_id)
  has_many(:reviews, dependent: :destroy)
  has_many(:approved_reviews, -> { approved }, class_name: 'Review')

  before_destroy -> { throw :abort if line_items.exists? }

  mount_uploader(:main_image, ImageUploader)
  mount_uploaders(:images, ImageUploader)

  monetize :price_cents
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Rectify::ControllerHelpers

  def show
    set_back_to_results_path
    present(ReviewsPresenter.new)
    @book = Books::GetBookWithAssociated.call(params[:id], load_reviews: true)
  end

  private

  def set_back_to_results_path
    referrer = request.referrer
    return unless referrer
    name = Rails.application.routes.recognize_path(referrer)[:controller]
    session[:back_to_results] = referrer if %w(home catalog).include?(name)
  end
end

app/views/books/_book.html.haml
.col-xs-6.col-sm-3
  .general-thumb-wrap
    .thumbnail.general-thumbnail
      = image_tag(book.main_image, alt: book.title,
        class: 'img img-shadow general-thumbnail-img')
      .thumb-hover
        .general-thumb-link-wrap
          = link_to(book_path(book), class: 'thumb-hover-link') do
            %i.fa.fa-eye.thumb-icon{'aria-hidden': 'true'}
          = link_to(ecomm.cart_items_path(id: book.id), method: :post,
            class: 'thumb-hover-link') do
            %i.fa.fa-shopping-cart.thumb-icon
  .general-thumb-info
    %p.pull-right.font-16.in-gold-500= number_to_currency(book.price)
    %p.general-title= truncate(book.title, length: 23)
    %span.divider-sm
    %p.in-grey-600.small= truncate(book.authors_short, length: 35)

app/views/books/_book_details.html.haml
%main.container
  = link_to((session[:back_to_results] || catalog_index_path),
    class: 'general-back-link') do
    %i.fa.fa-long-arrow-left.mr-15
    = t('.back_to_results')
  .row
    .col-sm-6
      .product-gallery
        .mb-20
          - unless @book.images.empty?
            = image_tag(@book.images.first, alt: @book.title,
              class: 'img-responsive', id: 'main-image')
          .images.clearfix
            - @book.images.each do |image|
              = link_to('#', class: 'img-link',
                'data-image': image.url) do
                = image_tag(image, alt: image)
    .col-sm-6
      %h1.mt-res-0= @book.title
      %p.in-grey-600.small= @book.authors_full
      .row
        .col-xs-12.col-md-4
          %p.h1.in-gold-500.mt-10= number_to_currency(@book.price)
        = form_tag(ecomm.cart_items_path, class: 'form-inline') do
          .col-xs-5.col-md-3
            .input-group.general-position
              %a.input-link.quantity-decrement{data: |
                {target: "quantities-#{@book.id}"}, href: '#'} |
                %i.fa.fa-minus.line-height-40
              = hidden_field_tag(:id, @book.id)
              %input.form-control.quantity-input{type: 'number', min: '1', |
                value: '1', name: 'quantity', id: "quantities-#{@book.id}"} |
            .input-group.general-position
              %a.input-link.quantity-increment{data: |
                {target: "quantities-#{@book.id}"}, href: '#'} |
                %i.fa.fa-plus.line-height-40
          .col-xs-7.col-md-5
            = submit_tag(t('.add_to_cart'),
              class: 'btn btn-default pull-right general-position')
      .pt-20.divider-lg
        %p= t('.description')
        %p#book-description.in-grey-600.small.line-height-2.text-justify
          = @book.description
      .pt-20.divider-lg
        .clearfix
          %p.general-item-info.pull-right= @book.year
          %p.break-word= t('.year')
      .pt-20.divider-lg
        .clearfix
          %p.general-item-info.pull-right= @book.dimensions
          %p.break-word= t('.dimensions')
      .pt-20.divider-lg
        .clearfix
          %p.general-item-info.pull-right= @book.materials_string
          %p.break-word= t('.materials')

app/views/books/_book_reviews.html.haml
%h3.in-gold-500.mb-25= "#{t('.reviews')} (#{@book.approved_reviews.size})"
.row
  .col-xs-12.col-sm-8
    %ul.media-list
      - @book.approved_reviews.each do |review|
        %li.media.divider-lg
          .media-left
            %span.img-circle.logo-size.logo-empty.media-object= |
              presenter.reviewer_name(review.user).first |
          .media-body
            %div
              %p.general-message-date.hidden-xs= l(review.updated_at,
                format: :long_date)
              %h4.media-heading.max-240.general-message-name
                %p= presenter.reviewer_name(review.user)
                - if presenter.verified_reviewer?(@book, review.user_id)
                  %span.general-message-verified= t('.verified_reviewer')
            .mb-15
              - 5.times do |index|
                %i.fa.fa-star.rate-star{class: |
                  ('rate-empty' if review.score < index + 1)} |
            %h4= review.title
            = markdown(review.body)
  .col-xs-12.col-sm-8
    = link_to(t('.write_review'), new_book_review_path(@book),
      class: 'btn btn-primary pull-right')

app/views/books/show.html.haml
= render('book_details')
.container
  .mb-80
    = render('book_reviews')