config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  get 'catalog/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  mount Ecomm::Engine => '/store'

  ActiveAdmin.routes(self)

  resources :books, only: :show do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :orders, only: [:index, :show]
  resource :settings, only: :show do
    resource :address, only: :update
    resource :email, only: :update
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include Rectify::ControllerHelpers

  before_action(:authenticate_user!)

  def index
    flash.keep
    redirect_to new_book_review_path(params[:book_id])
  end

  def new
    @book = Books::GetBookWithAssociated.call(params[:book_id])
    @review = ReviewForm.new(book_id: @book.id, score: 0)
  end

  def create
    Reviews::CreateReview.call(params, current_user) do
      on(:invalid) do |review, book|
        expose(review: review, book: book)
        render('new')
      end

      on(:ok) { |note| redirect_to book_path(params[:book_id]), notice: note }
    end
  end
end

app/views/reviews/_form.html.haml
.row
  .col-xs-12.col-sm-8
    %h3.in-gold-500.mb-25= t('.write_review')
    %p.font-weight-light= t('.score')
    - 5.times do |index|
      %i.fa.fa-2x.fa-star.rate-star.review-star{id: "star-#{index + 1}",
        class: ((@review.score < index + 1) ? 'rate-empty' : 'star-checked' )}
    = simple_form_for(@review, url: book_reviews_path) do |f|
      = f.input_field(:book_id, as: :hidden)
      = f.input_field(:score, as: :hidden)
      = f.input(:title)
      = f.input(:body, as: :text, input_html: { rows: 5 })
      = f.button(:submit, t('.post'), class: 'btn-default pull-right')

app/views/reviews/new.html.haml
= render('books/book_details')
.container
  .mb-80
    = render('form')